### ISSUE TITLE
Sync byte

### ISSUE THREAD

**Issue by FLYBYME** [simondlevy/SpektrumDSM#1]
How does this lib manage not getting out of sync with the dsm packet? If it started reading half way though a packet its going to be all wrong.

**Comment by simondlevy** [comment]
Read pages 89-91 of David McGriffy's [Make Drones](https://www.amazon.com/Make-Drones-Teach-Arduino-Fly/dp/1680451715) book.  He shows how you can use interrupts and timing to get error-free DSM signals.  My code is based on his.  The only way it goes wrong is if you try to sample the RX constantly, with no delay between samplings.  That's why my examples have a 10-msec delay in the [loop](https://github.com/simondlevy/SpektrumDSM/blob/master/examples/ReadSpektrum/ReadSpektrum.ino#L34-L55)() function.
